/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import Classes_UML.Tarefa;
import java.awt.Point;
/**
 *
 * @author Jeferson Alves
 */
public class BarraTarefa extends javax.swing.JPanel {

    /**
     * Creates new form BarraTarefa
     */
    
    public enum Cor{ VERDE, VERMELHA};
    
    public BarraTarefa(Tarefa tarefa, Point posicaoTela, boolean atrasado) {
        initComponents();
        indiceTarefaJLabel.setText(tarefa.getNome());
        porcentagemJLabel.setText(tarefa.getProgresso() + "%");
        double larguraCorreta = progressoJLabel.getIcon().getIconWidth();
        larguraCorreta = larguraCorreta * tarefa.getProgresso() * 0.01;
        progressoJLabel.setSize((int)larguraCorreta, 15);
        this.setBounds(posicaoTela.x, posicaoTela.y, 988, 76);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoEditarJButton = new javax.swing.JButton();
        statusJLabel = new javax.swing.JLabel();
        indiceTarefaJLabel = new javax.swing.JLabel();
        progressoJLabel = new javax.swing.JLabel();
        progressoFundoJLabel = new javax.swing.JLabel();
        porcentagemJLabel = new javax.swing.JLabel();
        fundoJLabel = new javax.swing.JLabel();
        fundoSombraJLabel = new javax.swing.JLabel();

        setBackground(new java.awt.Color(221, 221, 220));
        setPreferredSize(new java.awt.Dimension(988, 76));
        setLayout(null);

        botaoEditarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PlusTabIconStatic.png"))); // NOI18N
        botaoEditarJButton.setBorder(null);
        botaoEditarJButton.setBorderPainted(false);
        botaoEditarJButton.setContentAreaFilled(false);
        botaoEditarJButton.setFocusPainted(false);
        botaoEditarJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/PlusTabIconPressed.png"))); // NOI18N
        add(botaoEditarJButton);
        botaoEditarJButton.setBounds(930, 12, 50, 20);

        statusJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GreenSquareIcon.png"))); // NOI18N
        add(statusJLabel);
        statusJLabel.setBounds(20, 19, 16, 20);

        indiceTarefaJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 20)); // NOI18N
        indiceTarefaJLabel.setForeground(new java.awt.Color(13, 127, 63));
        indiceTarefaJLabel.setText("Tarefa 1");
        add(indiceTarefaJLabel);
        indiceTarefaJLabel.setBounds(40, 18, 782, 21);

        progressoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GreenBarIcon.png"))); // NOI18N
        add(progressoJLabel);
        progressoJLabel.setBounds(22, 42, 800, 15);

        progressoFundoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GreenBarBackgroundIcon.png"))); // NOI18N
        add(progressoFundoJLabel);
        progressoFundoJLabel.setBounds(20, 40, 804, 20);

        porcentagemJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 20)); // NOI18N
        porcentagemJLabel.setForeground(new java.awt.Color(13, 127, 63));
        porcentagemJLabel.setText("100%");
        add(porcentagemJLabel);
        porcentagemJLabel.setBounds(830, 40, 50, 21);

        fundoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TarefaBackgroundIcon.png"))); // NOI18N
        fundoJLabel.setText("jLabel5");
        add(fundoJLabel);
        fundoJLabel.setBounds(5, 8, 976, 64);

        fundoSombraJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/TarefaBackgroundShadowIcon.png"))); // NOI18N
        fundoSombraJLabel.setText("jLabel2");
        add(fundoSombraJLabel);
        fundoSombraJLabel.setBounds(0, 3, 988, 76);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEditarJButton;
    private javax.swing.JLabel fundoJLabel;
    private javax.swing.JLabel fundoSombraJLabel;
    private javax.swing.JLabel indiceTarefaJLabel;
    private javax.swing.JLabel porcentagemJLabel;
    private javax.swing.JLabel progressoFundoJLabel;
    private javax.swing.JLabel progressoJLabel;
    private javax.swing.JLabel statusJLabel;
    // End of variables declaration//GEN-END:variables
}
