/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;
import java.awt.Point;

/**
 *
 * @author Jeferson Alves
 */
public class EquipeMenuComponent extends javax.swing.JPanel {

    /**
     * Creates new form EquipeMenuComponent
     */
    public static Point posicaoProximoComponente = new Point(8, 17);
    private static boolean isGray = false;
    
    public EquipeMenuComponent(String nome) {
        System.out.println("Recebi nome " + nome);
        this.setBounds(posicaoProximoComponente.x, posicaoProximoComponente.y, 166, 13);
        posicaoProximoComponente.y += 13;
        initComponents();
        
        nomeMembroJLabel.setText(nome);
        if(isGray)
        {
            membroBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MembroGrayBackground.png")));
        }
        else
        {
            membroBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MembroWhiteBackground.png")));
        }
        isGray = !isGray;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nomeMembroJLabel = new javax.swing.JLabel();
        membroStatusJLabel = new javax.swing.JLabel();
        membroBackgroundJLabel = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(166, 13));
        setLayout(null);

        nomeMembroJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 12)); // NOI18N
        nomeMembroJLabel.setForeground(new java.awt.Color(91, 91, 91));
        nomeMembroJLabel.setText("Nome");
        add(nomeMembroJLabel);
        nomeMembroJLabel.setBounds(20, 0, 140, 13);

        membroStatusJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/GrayStatusCircle.png"))); // NOI18N
        add(membroStatusJLabel);
        membroStatusJLabel.setBounds(5, 0, 15, 15);

        membroBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MembroWhiteBackground.png"))); // NOI18N
        add(membroBackgroundJLabel);
        membroBackgroundJLabel.setBounds(0, 0, 170, 13);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel membroBackgroundJLabel;
    private javax.swing.JLabel membroStatusJLabel;
    private javax.swing.JLabel nomeMembroJLabel;
    // End of variables declaration//GEN-END:variables
}
