/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import Classes_UML.Serializador;
import java.util.Date;
import java.awt.Point;
import java.text.SimpleDateFormat;
import Classes_UML.Sistema;
import Classes_UML.Tarefa;
import Classes_UML.Usuario;
import java.awt.Frame;
import java.awt.Toolkit;
import java.util.ArrayList;
import java.text.ParseException;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author Jeferson Alves
 */
public class Principal extends javax.swing.JFrame {

    ArrayList<BarraTarefa> barras = new ArrayList<BarraTarefa>();
    ArrayList<EquipeMenuComponent> componentesChat = new ArrayList<EquipeMenuComponent>();
    //private Classes_UML.Tarefa tarefa;
    private ArrayList<Usuario> atribuidos;
    private ArrayList<Usuario> responsaveis;
    private Sistema sistema;
    private Tarefa tarefa;
    private Point posicaoProximaBarraInicial;
    private Point posicaoProximaBarra;
    private Usuario user;
    DefaultListModel<String> responsaveisListModel = new DefaultListModel<String>();
    DefaultListModel<String> membrosListModel = new DefaultListModel<String>();

    /**
     * Creates new form Principal
     */
    public Principal(Sistema sistema, Usuario user) {

        posicaoProximaBarraInicial = new Point(0, 117);
        posicaoProximaBarra = new Point(0, 117);
        this.user = user;

        this.setUndecorated(true);
        this.setAlwaysOnTop(true);
        this.setResizable(false);
        this.setVisible(true);
        initComponents();
        Toolkit tk = Toolkit.getDefaultToolkit();
        int largura = tk.getScreenSize().width;
        int altura = tk.getScreenSize().height;

        //System.out.println(user.getTarefas());

        criadorTarefaJPanel.setEnabled(false);
        criadorTarefaJPanel.setVisible(false);
        areaDireitaJLabel.setBounds(largura - 186, 0, 186, altura);
        ligarBarras(true);

        //progressoTarefasJPanel.setBounds(areaEsquerdaJLabel.getWidth()+3 , 160, 988, 112);
        //notificacoesJPanel.setBounds(areaEsquerdaJLabel.getWidth()+3,35 , 988, 112);
        //BarraTarefa t = new BarraTarefa(5, 0, Tarefa.Cor.VERDE);
        //progressoTarefasJPanel.add(t);
        //t.setVisible(true);
        //t.setBounds(0, 40, 976, 100);
        //tarefas.add(t);
        criadorTarefaJPanel.setVisible(false);
        criadorTarefaJPanel.setEnabled(false);

        membrosJList.removeAll();
        responsaveisJList.removeAll();
        for (int i = 0; i < sistema.getUsuarios().size(); i++) {
            membrosListModel.addElement(sistema.getUsuarios().get(i).getNome());
        }
        membrosJList.setModel(membrosListModel);

        this.sistema = sistema;
        criaMenuChat();
    }

    private void criaMenuChat() {
        for (Usuario u : sistema.getUsuarios()) {
            //System.out.println("adicionando o usuário " + u.getNome());
            EquipeMenuComponent componente = new EquipeMenuComponent(u.getNome());
            componente.setEnabled(true);
            componente.setVisible(true);
            equipeJPanel.add(componente);
            componentesChat.add(componente);
        }

        chatJPanel.setBounds(EquipeMenuComponent.posicaoProximoComponente.x - 3, EquipeMenuComponent.posicaoProximoComponente.y, 180, 142);
        contatosJLabel.setBounds(EquipeMenuComponent.posicaoProximoComponente.x - 5, EquipeMenuComponent.posicaoProximoComponente.y + chatJPanel.getSize().height + 3, 178, 255);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        upperTabLogoJLabel = new javax.swing.JLabel();
        encerrarJButton = new javax.swing.JButton();
        upperTabJLabel = new javax.swing.JLabel();
        criadorTarefaJPanel = new javax.swing.JPanel();
        novaTarefaJLabel = new javax.swing.JLabel();
        dataEntregaJLabel = new javax.swing.JLabel();
        responsaveisJLabel = new javax.swing.JLabel();
        descricaoJLabel = new javax.swing.JLabel();
        progressoJLabel = new javax.swing.JLabel();
        concluirJButton = new javax.swing.JButton();
        voltarJButton = new javax.swing.JButton();
        nomeTarefaJTextField = new javax.swing.JTextField();
        diaJTextField = new javax.swing.JTextField();
        mesJTextField = new javax.swing.JTextField();
        anoJTextField = new javax.swing.JTextField();
        primeiraBarraJLabel = new javax.swing.JLabel();
        segundaBarraJLabel = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descricaoJTextArea = new javax.swing.JTextArea();
        progressoTarefaJTextField = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        responsaveisJList = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        membrosJList = new javax.swing.JList<>();
        adicionarJButton = new javax.swing.JButton();
        removerJButton = new javax.swing.JButton();
        membrosProjetoJLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        criadorBackgroundJLabel = new javax.swing.JLabel();
        progressoTarefasJPanel = new javax.swing.JPanel();
        emAtrasoJButton = new javax.swing.JButton();
        emAndamentoJButton = new javax.swing.JButton();
        criarTarefaJButton = new javax.swing.JButton();
        progressoTarefasJLabel = new javax.swing.JLabel();
        progressoTarefasBackgroundJLabel = new javax.swing.JLabel();
        equipeJPanel = new javax.swing.JPanel();
        parceirosEquipeJLabel = new javax.swing.JLabel();
        contatosJLabel = new javax.swing.JLabel();
        chatJPanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        chatJTextArea = new javax.swing.JTextArea();
        chatEnviarJTextField = new javax.swing.JTextField();
        enviarJButton = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        notificacoesJPanel = new javax.swing.JPanel();
        notificacaoAbaJButton1 = new javax.swing.JButton();
        notificacao1JLabel = new javax.swing.JLabel();
        notificacao2JLabel = new javax.swing.JLabel();
        notificacao3JLabel = new javax.swing.JLabel();
        notificacao3AreaJLabel = new javax.swing.JLabel();
        notificacao2AreaJLabel = new javax.swing.JLabel();
        notificacao1AreaJLabel = new javax.swing.JLabel();
        notificacoesJLabel = new javax.swing.JLabel();
        notificacaoBackgroundJLabel = new javax.swing.JLabel();
        abaEsquerdaJPanel = new javax.swing.JPanel();
        reunioesJButton = new javax.swing.JButton();
        projetosJButton = new javax.swing.JButton();
        equipesJButton = new javax.swing.JButton();
        deliberacaoJButton = new javax.swing.JButton();
        cronogramaJButton = new javax.swing.JButton();
        avaliacaoParesJButton = new javax.swing.JButton();
        abaEsquerdaBackground = new javax.swing.JLabel();
        equipeJLabel = new javax.swing.JLabel();
        calendarioJLabel = new javax.swing.JLabel();
        areaDireitaJLabel = new javax.swing.JLabel();
        areaEsquerdaJLabel = new javax.swing.JLabel();
        areaCentroJLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1366, 768));
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setPreferredSize(new java.awt.Dimension(1366, 768));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        upperTabLogoJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/UpperTabLogo.png"))); // NOI18N
        getContentPane().add(upperTabLogoJLabel);
        upperTabLogoJLabel.setBounds(8, 1, 170, 33);

        encerrarJButton.setFont(new java.awt.Font("Ubuntu", 1, 12)); // NOI18N
        encerrarJButton.setText("X");
        encerrarJButton.setAlignmentX(0.5F);
        encerrarJButton.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        encerrarJButton.setMaximumSize(new java.awt.Dimension(17, 17));
        encerrarJButton.setMinimumSize(new java.awt.Dimension(17, 17));
        encerrarJButton.setPreferredSize(new java.awt.Dimension(17, 17));
        encerrarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                encerrarJButtonMouseClicked(evt);
            }
        });
        encerrarJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                encerrarJButtonActionPerformed(evt);
            }
        });
        getContentPane().add(encerrarJButton);
        encerrarJButton.setBounds(1332, 3, 30, 17);

        upperTabJLabel.setBackground(new java.awt.Color(40, 50, 113));
        upperTabJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/UpperTabIcon.png"))); // NOI18N
        getContentPane().add(upperTabJLabel);
        upperTabJLabel.setBounds(0, 0, 1366, 35);

        criadorTarefaJPanel.setBackground(new java.awt.Color(221, 221, 220));
        criadorTarefaJPanel.setLayout(null);

        novaTarefaJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        novaTarefaJLabel.setForeground(new java.awt.Color(91, 91, 91));
        novaTarefaJLabel.setText("Nova tarefa:");
        criadorTarefaJPanel.add(novaTarefaJLabel);
        novaTarefaJLabel.setBounds(20, 20, 90, 18);

        dataEntregaJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        dataEntregaJLabel.setForeground(new java.awt.Color(91, 91, 91));
        dataEntregaJLabel.setText("Data da entrega:");
        criadorTarefaJPanel.add(dataEntregaJLabel);
        dataEntregaJLabel.setBounds(20, 50, 120, 18);

        responsaveisJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        responsaveisJLabel.setForeground(new java.awt.Color(91, 91, 91));
        responsaveisJLabel.setText("Responsáveis:");
        criadorTarefaJPanel.add(responsaveisJLabel);
        responsaveisJLabel.setBounds(20, 80, 110, 18);

        descricaoJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        descricaoJLabel.setForeground(new java.awt.Color(91, 91, 91));
        descricaoJLabel.setText("Descrição:");
        criadorTarefaJPanel.add(descricaoJLabel);
        descricaoJLabel.setBounds(20, 210, 80, 18);

        progressoJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        progressoJLabel.setForeground(new java.awt.Color(91, 91, 91));
        progressoJLabel.setText("Progresso:");
        criadorTarefaJPanel.add(progressoJLabel);
        progressoJLabel.setBounds(835, 20, 80, 18);

        concluirJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ConcluirStaticIcon.png"))); // NOI18N
        concluirJButton.setBorder(null);
        concluirJButton.setBorderPainted(false);
        concluirJButton.setContentAreaFilled(false);
        concluirJButton.setFocusPainted(false);
        concluirJButton.setFocusable(false);
        concluirJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ConcluirPressedIcon.png"))); // NOI18N
        concluirJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                concluirJButtonMouseClicked(evt);
            }
        });
        criadorTarefaJPanel.add(concluirJButton);
        concluirJButton.setBounds(380, 320, 110, 27);

        voltarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/VoltarStaticIcon.png"))); // NOI18N
        voltarJButton.setBorder(null);
        voltarJButton.setBorderPainted(false);
        voltarJButton.setContentAreaFilled(false);
        voltarJButton.setFocusPainted(false);
        voltarJButton.setFocusable(false);
        voltarJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/VoltarPressedIcon.png"))); // NOI18N
        voltarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                voltarJButtonMouseClicked(evt);
            }
        });
        criadorTarefaJPanel.add(voltarJButton);
        voltarJButton.setBounds(490, 320, 110, 26);

        nomeTarefaJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        nomeTarefaJTextField.setForeground(new java.awt.Color(91, 91, 91));
        nomeTarefaJTextField.setText("Nome da tarefa");
        nomeTarefaJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        nomeTarefaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomeTarefaJTextFieldActionPerformed(evt);
            }
        });
        criadorTarefaJPanel.add(nomeTarefaJTextField);
        nomeTarefaJTextField.setBounds(110, 17, 660, 20);

        diaJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        diaJTextField.setForeground(new java.awt.Color(91, 91, 91));
        diaJTextField.setText("01");
        diaJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        criadorTarefaJPanel.add(diaJTextField);
        diaJTextField.setBounds(140, 48, 25, 20);

        mesJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        mesJTextField.setForeground(new java.awt.Color(91, 91, 91));
        mesJTextField.setText("01");
        mesJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mesJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mesJTextFieldActionPerformed(evt);
            }
        });
        criadorTarefaJPanel.add(mesJTextField);
        mesJTextField.setBounds(180, 48, 25, 20);

        anoJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        anoJTextField.setForeground(new java.awt.Color(91, 91, 91));
        anoJTextField.setText("2018");
        anoJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        anoJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anoJTextFieldActionPerformed(evt);
            }
        });
        criadorTarefaJPanel.add(anoJTextField);
        anoJTextField.setBounds(220, 48, 45, 20);

        primeiraBarraJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        primeiraBarraJLabel.setForeground(new java.awt.Color(91, 91, 91));
        primeiraBarraJLabel.setText("/");
        criadorTarefaJPanel.add(primeiraBarraJLabel);
        primeiraBarraJLabel.setBounds(170, 50, 10, 18);

        segundaBarraJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        segundaBarraJLabel.setForeground(new java.awt.Color(91, 91, 91));
        segundaBarraJLabel.setText("/");
        criadorTarefaJPanel.add(segundaBarraJLabel);
        segundaBarraJLabel.setBounds(210, 50, 20, 18);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        descricaoJTextArea.setColumns(20);
        descricaoJTextArea.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        descricaoJTextArea.setForeground(new java.awt.Color(91, 91, 91));
        descricaoJTextArea.setRows(5);
        descricaoJTextArea.setText("Descrição da tarefa aqui");
        descricaoJTextArea.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        descricaoJTextArea.setSelectionColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(descricaoJTextArea);

        criadorTarefaJPanel.add(jScrollPane1);
        jScrollPane1.setBounds(105, 210, 865, 100);

        progressoTarefaJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        progressoTarefaJTextField.setForeground(new java.awt.Color(91, 91, 91));
        progressoTarefaJTextField.setText("0");
        progressoTarefaJTextField.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        progressoTarefaJTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                progressoTarefaJTextFieldActionPerformed(evt);
            }
        });
        criadorTarefaJPanel.add(progressoTarefaJTextField);
        progressoTarefaJTextField.setBounds(920, 17, 30, 22);

        jButton3.setBorder(null);
        jButton3.setBorderPainted(false);
        jButton3.setContentAreaFilled(false);
        jButton3.setFocusPainted(false);
        jButton3.setFocusable(false);
        criadorTarefaJPanel.add(jButton3);
        jButton3.setBounds(100, 190, 0, 0);

        jButton4.setBorder(null);
        jButton4.setBorderPainted(false);
        jButton4.setContentAreaFilled(false);
        jButton4.setFocusPainted(false);
        jButton4.setFocusable(false);
        criadorTarefaJPanel.add(jButton4);
        jButton4.setBounds(290, 190, 0, 0);

        jScrollPane2.setBorder(null);

        responsaveisJList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        responsaveisJList.setFont(new java.awt.Font("Helvetica Light", 0, 12)); // NOI18N
        responsaveisJList.setForeground(new java.awt.Color(91, 91, 91));
        jScrollPane2.setViewportView(responsaveisJList);

        criadorTarefaJPanel.add(jScrollPane2);
        jScrollPane2.setBounds(130, 80, 100, 80);

        jScrollPane3.setBorder(null);

        membrosJList.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        membrosJList.setFont(new java.awt.Font("Helvetica Light", 0, 12)); // NOI18N
        membrosJList.setForeground(new java.awt.Color(91, 91, 91));
        jScrollPane3.setViewportView(membrosJList);

        criadorTarefaJPanel.add(jScrollPane3);
        jScrollPane3.setBounds(860, 80, 100, 80);

        adicionarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AdicionarStaticIcon.png"))); // NOI18N
        adicionarJButton.setBorder(null);
        adicionarJButton.setBorderPainted(false);
        adicionarJButton.setContentAreaFilled(false);
        adicionarJButton.setFocusPainted(false);
        adicionarJButton.setFocusable(false);
        adicionarJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AdicionarPressedIcon.png"))); // NOI18N
        adicionarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adicionarJButtonMouseClicked(evt);
            }
        });
        criadorTarefaJPanel.add(adicionarJButton);
        adicionarJButton.setBounds(850, 160, 120, 35);

        removerJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/RemoverStaticIcon.png"))); // NOI18N
        removerJButton.setBorder(null);
        removerJButton.setBorderPainted(false);
        removerJButton.setContentAreaFilled(false);
        removerJButton.setFocusPainted(false);
        removerJButton.setFocusable(false);
        removerJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/RemoverPressedIcon.png"))); // NOI18N
        removerJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                removerJButtonMouseClicked(evt);
            }
        });
        criadorTarefaJPanel.add(removerJButton);
        removerJButton.setBounds(120, 160, 120, 35);

        membrosProjetoJLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        membrosProjetoJLabel.setForeground(new java.awt.Color(91, 91, 91));
        membrosProjetoJLabel.setText("Membros do projeto:");
        criadorTarefaJPanel.add(membrosProjetoJLabel);
        membrosProjetoJLabel.setBounds(710, 80, 150, 18);

        jLabel1.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(91, 91, 91));
        jLabel1.setText("%");
        criadorTarefaJPanel.add(jLabel1);
        jLabel1.setBounds(950, 20, 14, 18);

        criadorBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CriadorBackgroundShadowIcon.png"))); // NOI18N
        criadorBackgroundJLabel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        criadorTarefaJPanel.add(criadorBackgroundJLabel);
        criadorBackgroundJLabel.setBounds(0, 0, 988, 367);

        getContentPane().add(criadorTarefaJPanel);
        criadorTarefaJPanel.setBounds(189, 260, 988, 370);

        progressoTarefasJPanel.setBackground(new java.awt.Color(221, 221, 220));
        progressoTarefasJPanel.setLayout(null);

        emAtrasoJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EmAtrasoStaticIcon.png"))); // NOI18N
        emAtrasoJButton.setBorder(null);
        emAtrasoJButton.setBorderPainted(false);
        emAtrasoJButton.setContentAreaFilled(false);
        emAtrasoJButton.setFocusable(false);
        emAtrasoJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EmAtrasoPressedIcon.png"))); // NOI18N
        progressoTarefasJPanel.add(emAtrasoJButton);
        emAtrasoJButton.setBounds(20, 78, 145, 24);

        emAndamentoJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EmAndamentoStaticIcon.png"))); // NOI18N
        emAndamentoJButton.setBorder(null);
        emAndamentoJButton.setBorderPainted(false);
        emAndamentoJButton.setContentAreaFilled(false);
        emAndamentoJButton.setFocusable(false);
        emAndamentoJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EmAndamentoPressedIcon.png"))); // NOI18N
        emAndamentoJButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emAndamentoJButtonActionPerformed(evt);
            }
        });
        progressoTarefasJPanel.add(emAndamentoJButton);
        emAndamentoJButton.setBounds(20, 49, 145, 24);

        criarTarefaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CriarTarefaStaticIcon.png"))); // NOI18N
        criarTarefaJButton.setBorder(null);
        criarTarefaJButton.setBorderPainted(false);
        criarTarefaJButton.setContentAreaFilled(false);
        criarTarefaJButton.setFocusable(false);
        criarTarefaJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CriarTarefaPressedIcon.png"))); // NOI18N
        criarTarefaJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                criarTarefaJButtonMouseClicked(evt);
            }
        });
        progressoTarefasJPanel.add(criarTarefaJButton);
        criarTarefaJButton.setBounds(800, 78, 166, 24);

        progressoTarefasJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ProgressoTarefasIcon.png"))); // NOI18N
        progressoTarefasJPanel.add(progressoTarefasJLabel);
        progressoTarefasJLabel.setBounds(6, 5, 976, 40);

        progressoTarefasBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NotificacaoShadowBackground.png"))); // NOI18N
        progressoTarefasJPanel.add(progressoTarefasBackgroundJLabel);
        progressoTarefasBackgroundJLabel.setBounds(0, 0, 988, 112);

        getContentPane().add(progressoTarefasJPanel);
        progressoTarefasJPanel.setBounds(189, 150, 988, 620);

        equipeJPanel.setBackground(new java.awt.Color(221, 221, 220));
        equipeJPanel.setLayout(null);

        parceirosEquipeJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ParceirosDeEquipeHeader.png"))); // NOI18N
        parceirosEquipeJLabel.setText("jLabel2");
        equipeJPanel.add(parceirosEquipeJLabel);
        parceirosEquipeJLabel.setBounds(8, 0, 166, 17);

        contatosJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MenuContatosStatic.png"))); // NOI18N
        equipeJPanel.add(contatosJLabel);
        contatosJLabel.setBounds(0, 160, 178, 255);

        chatJPanel.setBackground(new java.awt.Color(221, 221, 220));
        chatJPanel.setLayout(null);

        jScrollPane4.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        chatJTextArea.setColumns(20);
        chatJTextArea.setRows(5);
        jScrollPane4.setViewportView(chatJTextArea);

        chatJPanel.add(jScrollPane4);
        jScrollPane4.setBounds(10, 10, 150, 87);

        chatEnviarJTextField.setFont(new java.awt.Font("Helvetica Light", 0, 12)); // NOI18N
        chatEnviarJTextField.setForeground(new java.awt.Color(91, 91, 91));
        chatEnviarJTextField.setCaretColor(new java.awt.Color(91, 91, 91));
        chatJPanel.add(chatEnviarJTextField);
        chatEnviarJTextField.setBounds(10, 110, 110, 16);

        enviarJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EnviarStaticIcon.png"))); // NOI18N
        enviarJButton.setBorder(null);
        enviarJButton.setBorderPainted(false);
        enviarJButton.setContentAreaFilled(false);
        enviarJButton.setFocusPainted(false);
        enviarJButton.setFocusable(false);
        enviarJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EnviarPressedIcon.png"))); // NOI18N
        enviarJButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enviarJButtonMouseClicked(evt);
            }
        });
        chatJPanel.add(enviarJButton);
        enviarJButton.setBounds(125, 108, 40, 20);

        jLabel3.setBackground(new java.awt.Color(221, 221, 220));
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ChatEquipeShadowBackground.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        chatJPanel.add(jLabel3);
        jLabel3.setBounds(-3, 0, 180, 142);
        jLabel3.getAccessibleContext().setAccessibleName("");

        equipeJPanel.add(chatJPanel);
        chatJPanel.setBounds(5, 12, 180, 142);

        getContentPane().add(equipeJPanel);
        equipeJPanel.setBounds(1185, 120, 180, 650);

        notificacoesJPanel.setBackground(new java.awt.Color(221, 221, 220));
        notificacoesJPanel.setLayout(null);

        notificacaoAbaJButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SelectTabStaticIcon.png"))); // NOI18N
        notificacaoAbaJButton1.setBorder(null);
        notificacaoAbaJButton1.setBorderPainted(false);
        notificacaoAbaJButton1.setContentAreaFilled(false);
        notificacaoAbaJButton1.setFocusable(false);
        notificacaoAbaJButton1.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/SelectTabPressedIcon.png"))); // NOI18N
        notificacoesJPanel.add(notificacaoAbaJButton1);
        notificacaoAbaJButton1.setBounds(945, 5, 30, 30);

        notificacao1JLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        notificacao1JLabel.setForeground(new java.awt.Color(91, 91, 91));
        notificacao1JLabel.setText("Notificação 1");
        notificacoesJPanel.add(notificacao1JLabel);
        notificacao1JLabel.setBounds(35, 46, 920, 20);

        notificacao2JLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        notificacao2JLabel.setForeground(new java.awt.Color(91, 91, 91));
        notificacao2JLabel.setText("Notificação 2");
        notificacoesJPanel.add(notificacao2JLabel);
        notificacao2JLabel.setBounds(35, 66, 920, 20);

        notificacao3JLabel.setFont(new java.awt.Font("Helvetica Light", 0, 15)); // NOI18N
        notificacao3JLabel.setForeground(new java.awt.Color(91, 91, 91));
        notificacao3JLabel.setText("Notificação 3");
        notificacoesJPanel.add(notificacao3JLabel);
        notificacao3JLabel.setBounds(35, 86, 920, 20);

        notificacao3AreaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/UnicaNotificacaoGrayIcon.png"))); // NOI18N
        notificacoesJPanel.add(notificacao3AreaJLabel);
        notificacao3AreaJLabel.setBounds(6, 86, 976, 20);

        notificacao2AreaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/UnicaNotificacaoWhiteIcon.png"))); // NOI18N
        notificacoesJPanel.add(notificacao2AreaJLabel);
        notificacao2AreaJLabel.setBounds(6, 66, 976, 20);

        notificacao1AreaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/UnicaNotificacaoGrayIcon.png"))); // NOI18N
        notificacoesJPanel.add(notificacao1AreaJLabel);
        notificacao1AreaJLabel.setBounds(6, 46, 976, 20);

        notificacoesJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NotificacoesIcon.png"))); // NOI18N
        notificacoesJPanel.add(notificacoesJLabel);
        notificacoesJLabel.setBounds(6, 5, 976, 40);

        notificacaoBackgroundJLabel.setBackground(new java.awt.Color(221, 221, 220));
        notificacaoBackgroundJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/NotificacaoShadowBackground.png"))); // NOI18N
        notificacoesJPanel.add(notificacaoBackgroundJLabel);
        notificacaoBackgroundJLabel.setBounds(0, 0, 988, 112);

        getContentPane().add(notificacoesJPanel);
        notificacoesJPanel.setBounds(189, 35, 988, 112);

        abaEsquerdaJPanel.setBackground(new java.awt.Color(255, 255, 255));
        abaEsquerdaJPanel.setMaximumSize(new java.awt.Dimension(172, 194));
        abaEsquerdaJPanel.setMinimumSize(new java.awt.Dimension(172, 194));
        abaEsquerdaJPanel.setLayout(null);

        reunioesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ReunioesIconStatic.png"))); // NOI18N
        reunioesJButton.setBorder(null);
        reunioesJButton.setBorderPainted(false);
        reunioesJButton.setContentAreaFilled(false);
        reunioesJButton.setFocusable(false);
        reunioesJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ReunioesIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(reunioesJButton);
        reunioesJButton.setBounds(1, 158, 170, 30);

        projetosJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ProjetosIconStatic.png"))); // NOI18N
        projetosJButton.setBorder(null);
        projetosJButton.setBorderPainted(false);
        projetosJButton.setContentAreaFilled(false);
        projetosJButton.setFocusPainted(false);
        projetosJButton.setFocusable(false);
        projetosJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ProjetosIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(projetosJButton);
        projetosJButton.setBounds(1, 127, 170, 30);

        equipesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EquipesIconStatic.png"))); // NOI18N
        equipesJButton.setBorder(null);
        equipesJButton.setBorderPainted(false);
        equipesJButton.setContentAreaFilled(false);
        equipesJButton.setFocusPainted(false);
        equipesJButton.setFocusable(false);
        equipesJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EquipesIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(equipesJButton);
        equipesJButton.setBounds(1, 98, 170, 27);

        deliberacaoJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DeliberacaoIconStatic.png"))); // NOI18N
        deliberacaoJButton.setBorder(null);
        deliberacaoJButton.setBorderPainted(false);
        deliberacaoJButton.setContentAreaFilled(false);
        deliberacaoJButton.setFocusPainted(false);
        deliberacaoJButton.setFocusable(false);
        deliberacaoJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/DeliberacaoIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(deliberacaoJButton);
        deliberacaoJButton.setBounds(1, 60, 170, 40);

        cronogramaJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CronogramaIconStatic.png"))); // NOI18N
        cronogramaJButton.setBorder(null);
        cronogramaJButton.setBorderPainted(false);
        cronogramaJButton.setContentAreaFilled(false);
        cronogramaJButton.setFocusable(false);
        cronogramaJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CronogramaIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(cronogramaJButton);
        cronogramaJButton.setBounds(1, 36, 170, 27);

        avaliacaoParesJButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AvaliacaoParesIconStatic.png"))); // NOI18N
        avaliacaoParesJButton.setBorder(null);
        avaliacaoParesJButton.setBorderPainted(false);
        avaliacaoParesJButton.setContentAreaFilled(false);
        avaliacaoParesJButton.setFocusPainted(false);
        avaliacaoParesJButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/AvaliacaoParesIconPressed.png"))); // NOI18N
        abaEsquerdaJPanel.add(avaliacaoParesJButton);
        avaliacaoParesJButton.setBounds(1, 5, 170, 27);

        abaEsquerdaBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/ButtonsTabLeft.png"))); // NOI18N
        abaEsquerdaJPanel.add(abaEsquerdaBackground);
        abaEsquerdaBackground.setBounds(0, 0, 172, 194);

        getContentPane().add(abaEsquerdaJPanel);
        abaEsquerdaJPanel.setBounds(6, 35, 172, 194);

        equipeJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/MenuEquipeStatic.png"))); // NOI18N
        getContentPane().add(equipeJLabel);
        equipeJLabel.setBounds(1187, 35, 178, 77);

        calendarioJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CalendarioIconFinal.png"))); // NOI18N
        getContentPane().add(calendarioJLabel);
        calendarioJLabel.setBounds(3, 230, 179, 132);

        areaDireitaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LeftTabBackground.png"))); // NOI18N
        getContentPane().add(areaDireitaJLabel);
        areaDireitaJLabel.setBounds(1180, 0, 186, 768);

        areaEsquerdaJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/LeftTabBackground.png"))); // NOI18N
        getContentPane().add(areaEsquerdaJLabel);
        areaEsquerdaJLabel.setBounds(0, 0, 186, 768);

        areaCentroJLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/CenterTabBackground.png"))); // NOI18N
        getContentPane().add(areaCentroJLabel);
        areaCentroJLabel.setBounds(189, 0, 988, 768);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void emAndamentoJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emAndamentoJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emAndamentoJButtonActionPerformed

    private void anoJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anoJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_anoJTextFieldActionPerformed

    private void mesJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mesJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mesJTextFieldActionPerformed

    private void nomeTarefaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomeTarefaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomeTarefaJTextFieldActionPerformed

    private void ligarBarras(boolean ligar) {
        if (ligar) {
            for (BarraTarefa bt : barras) {
                bt.setVisible(false);
                bt.setEnabled(false);

                posicaoProximaBarra.x = posicaoProximaBarraInicial.x;
                posicaoProximaBarra.y = posicaoProximaBarraInicial.y;
            }
            barras.clear();

            for (Tarefa t : user.getTarefas()) {
                BarraTarefa bt = new BarraTarefa(t, posicaoProximaBarra, false);
                barras.add(bt);
                posicaoProximaBarra.y += 80;
                progressoTarefasJPanel.add(bt);
                bt.setEnabled(true);
                bt.setVisible(true);
            }
        }
    }

    private void progressoTarefaJTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_progressoTarefaJTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_progressoTarefaJTextFieldActionPerformed

    private void concluirJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_concluirJButtonMouseClicked
        String nomeTarefa = nomeTarefaJTextField.getText();
        String descricaoTarefa = descricaoJTextArea.getText();
        int progressoTarefa = Integer.valueOf(progressoTarefaJTextField.getText());

        String diaPrazo = diaJTextField.getText();
        String mesPrazo = mesJTextField.getText();
        String anoPrazo = anoJTextField.getText();

        SimpleDateFormat formatoData = new SimpleDateFormat("dd/MM/yyyy");

        String s = diaPrazo;
        s += "/";
        s += mesPrazo;
        s += "/";
        s += anoPrazo;

        Date dataHoje = new Date();
        Date dataPrazo = null;

        boolean podeGravarTarefa = true;
        
        

        try {
            dataPrazo = formatoData.parse(s);
            
            if (dataPrazo.before(dataHoje)) {
                // Mensagem de alerta
                JOptionPane.showMessageDialog(new Frame(), "Data de prazo inválida!");
                podeGravarTarefa = false;
            }
        } catch (ParseException e) {
            // Mensagem de alerta
            podeGravarTarefa = false;
        }
        
        if (atribuidos.isEmpty()) {
            JOptionPane.showMessageDialog(new Frame(), "Você precisa atribuir ao menos 1 pessoa à tarefa.");
            podeGravarTarefa = false;
        }

        if (podeGravarTarefa) {
            tarefa = new Tarefa("Nova Tarefa", "Insira descricao da tarefa aqui", new Date());
            for (Usuario u : atribuidos) {
                tarefa.addUsuarioAtribuido(u);
                u.adicionaNovaTarefa(tarefa);
                //System.out.println("Tarefa atribuída ao usuário " + u.getNome());
            }

            if (dataPrazo != null) {
                tarefa.setPrazo(dataPrazo);
            }

            tarefa.setDescricao(descricaoTarefa);
            tarefa.setNome(nomeTarefa);
            tarefa.setProgresso(progressoTarefa);
            
            // Desliga o painel criador de nova tarefa
            criadorTarefaJPanel.setEnabled(false);
            criadorTarefaJPanel.setVisible(false);

            // Liga todas as barras de tarefa
            ligarBarras(true);
        }

    }//GEN-LAST:event_concluirJButtonMouseClicked

    private void voltarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_voltarJButtonMouseClicked
        // Desliga o painel criador de nova tarefa
        criadorTarefaJPanel.setEnabled(false);
        criadorTarefaJPanel.setVisible(false);
        // Liga todas as barras de tarefa
        ligarBarras(true);
    }//GEN-LAST:event_voltarJButtonMouseClicked

    private void adicionarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adicionarJButtonMouseClicked
        if (!membrosJList.isSelectionEmpty()) {
            // Adicionar na JList dos responsáveis
            int index = membrosJList.getSelectedIndex();
            String nome = membrosJList.getSelectedValue();
            responsaveisListModel.addElement(membrosJList.getSelectedValue());
            responsaveisJList.setModel(responsaveisListModel);

            // Remove da JList dos membros
            membrosListModel.remove(index);
            membrosJList.setModel(membrosListModel);
            membrosJList.clearSelection();

            for (Usuario usr : sistema.getUsuarios()) {
                if (usr.getNome().equals(nome)) {
                    atribuidos.add(usr);
                    break;
                }
            }

            //System.out.println(atribuidos);
        }
    }//GEN-LAST:event_adicionarJButtonMouseClicked

    private Usuario pegaUsuarioPorIndice(int indice) {
        return sistema.getUsuarios().get(indice);
    }

    private void removerJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_removerJButtonMouseClicked
        if (!responsaveisJList.isSelectionEmpty()) {
            // Adicionar na JList dos membros
            int index = responsaveisJList.getSelectedIndex();
            membrosListModel.addElement(responsaveisJList.getSelectedValue());
            membrosJList.setModel(membrosListModel);

            // Remove da JList dos responsáveis
            responsaveisListModel.remove(index);
            responsaveisJList.setModel(responsaveisListModel);
            responsaveisJList.clearSelection();
        }
    }//GEN-LAST:event_removerJButtonMouseClicked

    private void criarTarefaJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_criarTarefaJButtonMouseClicked
        if (criadorTarefaJPanel.isEnabled() == false) {
            // Desliga tarefas
            // Liga o painel
            criadorTarefaJPanel.setEnabled(true);
            criadorTarefaJPanel.setVisible(true);

            // Inicializa os campos da nova tarefa
            nomeTarefaJTextField.setText("Nome da tarefa");
            Calendar hoje = Calendar.getInstance();
            Integer dia = hoje.get(Calendar.DAY_OF_MONTH);
            Integer mes = hoje.get(Calendar.MONTH);
            Integer ano = hoje.get(Calendar.YEAR);
            diaJTextField.setText((++dia).toString());
            mesJTextField.setText((++mes).toString());
            anoJTextField.setText(ano.toString());
            progressoTarefaJTextField.setText("0");
            descricaoJTextArea.setText("Descrição da tarefa aqui");
            atribuidos = new ArrayList<>();

            responsaveisListModel.clear();
            membrosListModel.clear();
            for (int i = 0; i < sistema.getUsuarios().size(); i++) {
                membrosListModel.addElement(sistema.getUsuarios().get(i).getNome());
            }
            responsaveisJList.setModel(responsaveisListModel);
            membrosJList.setModel(membrosListModel);

        } else {
            // Liga tarefas
            // Desliga o Painel
            criadorTarefaJPanel.setEnabled(false);
            criadorTarefaJPanel.setVisible(false);
        }
    }//GEN-LAST:event_criarTarefaJButtonMouseClicked

    private void enviarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enviarJButtonMouseClicked
        String enviar = "";
        if (!chatJTextArea.getText().isEmpty()) {
            enviar = chatJTextArea.getText() + "\n";
        }
        enviar += user.getNome() + ":\n";
        enviar += chatEnviarJTextField.getText();
        if (!chatEnviarJTextField.getText().isEmpty()) {
            chatJTextArea.setText(enviar);
            chatEnviarJTextField.setText("");
        }
    }//GEN-LAST:event_enviarJButtonMouseClicked

    private void encerrarJButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_encerrarJButtonMouseClicked
        // TODO add your handling code here:
        Login tela = new Login(sistema);
        this.setVisible(false);
        tela.setVisible(true);
        Serializador.gravaSistema(sistema);
        this.dispose();
    }//GEN-LAST:event_encerrarJButtonMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:

    }//GEN-LAST:event_formWindowClosing

    private void encerrarJButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_encerrarJButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_encerrarJButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel abaEsquerdaBackground;
    private javax.swing.JPanel abaEsquerdaJPanel;
    private javax.swing.JButton adicionarJButton;
    private javax.swing.JTextField anoJTextField;
    private javax.swing.JLabel areaCentroJLabel;
    private javax.swing.JLabel areaDireitaJLabel;
    private javax.swing.JLabel areaEsquerdaJLabel;
    private javax.swing.JButton avaliacaoParesJButton;
    private javax.swing.JLabel calendarioJLabel;
    private javax.swing.JTextField chatEnviarJTextField;
    private javax.swing.JPanel chatJPanel;
    private javax.swing.JTextArea chatJTextArea;
    private javax.swing.JButton concluirJButton;
    private javax.swing.JLabel contatosJLabel;
    private javax.swing.JLabel criadorBackgroundJLabel;
    private javax.swing.JPanel criadorTarefaJPanel;
    private javax.swing.JButton criarTarefaJButton;
    private javax.swing.JButton cronogramaJButton;
    private javax.swing.JLabel dataEntregaJLabel;
    private javax.swing.JButton deliberacaoJButton;
    private javax.swing.JLabel descricaoJLabel;
    private javax.swing.JTextArea descricaoJTextArea;
    private javax.swing.JTextField diaJTextField;
    private javax.swing.JButton emAndamentoJButton;
    private javax.swing.JButton emAtrasoJButton;
    private javax.swing.JButton encerrarJButton;
    private javax.swing.JButton enviarJButton;
    private javax.swing.JLabel equipeJLabel;
    private javax.swing.JPanel equipeJPanel;
    private javax.swing.JButton equipesJButton;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> membrosJList;
    private javax.swing.JLabel membrosProjetoJLabel;
    private javax.swing.JTextField mesJTextField;
    private javax.swing.JTextField nomeTarefaJTextField;
    private javax.swing.JLabel notificacao1AreaJLabel;
    private javax.swing.JLabel notificacao1JLabel;
    private javax.swing.JLabel notificacao2AreaJLabel;
    private javax.swing.JLabel notificacao2JLabel;
    private javax.swing.JLabel notificacao3AreaJLabel;
    private javax.swing.JLabel notificacao3JLabel;
    private javax.swing.JButton notificacaoAbaJButton1;
    private javax.swing.JLabel notificacaoBackgroundJLabel;
    private javax.swing.JLabel notificacoesJLabel;
    private javax.swing.JPanel notificacoesJPanel;
    private javax.swing.JLabel novaTarefaJLabel;
    private javax.swing.JLabel parceirosEquipeJLabel;
    private javax.swing.JLabel primeiraBarraJLabel;
    private javax.swing.JLabel progressoJLabel;
    private javax.swing.JTextField progressoTarefaJTextField;
    private javax.swing.JLabel progressoTarefasBackgroundJLabel;
    private javax.swing.JLabel progressoTarefasJLabel;
    private javax.swing.JPanel progressoTarefasJPanel;
    private javax.swing.JButton projetosJButton;
    private javax.swing.JButton removerJButton;
    private javax.swing.JLabel responsaveisJLabel;
    private javax.swing.JList<String> responsaveisJList;
    private javax.swing.JButton reunioesJButton;
    private javax.swing.JLabel segundaBarraJLabel;
    private javax.swing.JLabel upperTabJLabel;
    private javax.swing.JLabel upperTabLogoJLabel;
    private javax.swing.JButton voltarJButton;
    // End of variables declaration//GEN-END:variables
}
